import jsPDF from 'jspdf';
import type { AdminLibraryItem } from '@/lib/adminLibrary';

// Aetheris brand palette (RGB)
const COLOR = {
  bg: [15, 15, 20] as [number, number, number],          // dark charcoal
  card: [26, 26, 32] as [number, number, number],
  border: [55, 55, 65] as [number, number, number],
  amber: [217, 167, 71] as [number, number, number],     // primary accent
  amberSoft: [60, 45, 20] as [number, number, number],
  text: [240, 240, 245] as [number, number, number],
  muted: [165, 165, 175] as [number, number, number],
  white: [255, 255, 255] as [number, number, number],
  red: [220, 90, 90] as [number, number, number],
  blue: [110, 165, 230] as [number, number, number],
};

const TOOL_LABELS: Record<string, string> = {
  social_content: 'Social Content Pack',
  sales_scripts: 'Sales Scripts',
  content_calendar: '30-Day Content Calendar',
  follow_up_plan: 'Follow-Up Plan',
  strategic_questions: 'Strategic Questions',
  brand_contradictions: 'Brand Contradictions Audit',
  friction_audit: 'Friction Vocabulary Audit',
  playbook: 'Strategic Playbook',
};

const PAGE_W = 210;
const PAGE_H = 297;
const MARGIN = 16;
const CONTENT_W = PAGE_W - MARGIN * 2;

class PdfBuilder {
  doc: jsPDF;
  y: number = MARGIN;
  pageNum: number = 1;
  title: string;
  toolLabel: string;

  constructor(title: string, toolLabel: string) {
    this.doc = new jsPDF({ unit: 'mm', format: 'a4' });
    this.title = title;
    this.toolLabel = toolLabel;
    this.paintBackground();
  }

  paintBackground() {
    this.doc.setFillColor(...COLOR.bg);
    this.doc.rect(0, 0, PAGE_W, PAGE_H, 'F');
  }

  ensure(needed: number) {
    if (this.y + needed > PAGE_H - 22) this.newPage();
  }

  newPage() {
    this.drawFooter();
    this.doc.addPage();
    this.pageNum++;
    this.paintBackground();
    this.y = MARGIN;
    this.drawRunningHeader();
  }

  drawRunningHeader() {
    this.doc.setFillColor(...COLOR.amber);
    this.doc.rect(0, 0, PAGE_W, 1.2, 'F');
    this.doc.setFont('helvetica', 'bold');
    this.doc.setFontSize(8);
    this.doc.setTextColor(...COLOR.amber);
    this.doc.text('AETHERIS', MARGIN, 8);
    this.doc.setFont('helvetica', 'normal');
    this.doc.setTextColor(...COLOR.muted);
    this.doc.text(this.toolLabel.toUpperCase(), PAGE_W - MARGIN, 8, { align: 'right' });
    this.y = 16;
  }

  drawFooter() {
    const fy = PAGE_H - 10;
    this.doc.setDrawColor(...COLOR.border);
    this.doc.setLineWidth(0.2);
    this.doc.line(MARGIN, fy - 4, PAGE_W - MARGIN, fy - 4);
    this.doc.setFont('helvetica', 'normal');
    this.doc.setFontSize(7.5);
    this.doc.setTextColor(...COLOR.muted);
    this.doc.text('aetheris.technology', MARGIN, fy);
    this.doc.text(`Page ${this.pageNum}`, PAGE_W - MARGIN, fy, { align: 'right' });
  }

  drawCover() {
    // Amber band
    this.doc.setFillColor(...COLOR.amber);
    this.doc.rect(0, 0, PAGE_W, 4, 'F');

    // Logo / brand
    this.doc.setFont('helvetica', 'bold');
    this.doc.setFontSize(11);
    this.doc.setTextColor(...COLOR.amber);
    this.doc.text('AETHERIS', MARGIN, 26);
    this.doc.setFont('helvetica', 'normal');
    this.doc.setFontSize(8);
    this.doc.setTextColor(...COLOR.muted);
    this.doc.text('AI Studio · Indianapolis', MARGIN, 31);

    // Tool label chip
    this.doc.setFillColor(...COLOR.amberSoft);
    this.doc.roundedRect(MARGIN, 70, 70, 8, 1.5, 1.5, 'F');
    this.doc.setFont('helvetica', 'bold');
    this.doc.setFontSize(8);
    this.doc.setTextColor(...COLOR.amber);
    this.doc.text(this.toolLabel.toUpperCase(), MARGIN + 4, 75.5);

    // Title
    this.doc.setFont('helvetica', 'bold');
    this.doc.setFontSize(28);
    this.doc.setTextColor(...COLOR.white);
    const titleLines = this.doc.splitTextToSize(this.title, CONTENT_W);
    this.doc.text(titleLines, MARGIN, 92);

    // Divider
    const dividerY = 92 + titleLines.length * 11 + 8;
    this.doc.setDrawColor(...COLOR.amber);
    this.doc.setLineWidth(0.6);
    this.doc.line(MARGIN, dividerY, MARGIN + 30, dividerY);

    // Meta
    this.doc.setFont('helvetica', 'normal');
    this.doc.setFontSize(10);
    this.doc.setTextColor(...COLOR.muted);
    this.doc.text(`Generated ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`, MARGIN, dividerY + 8);

    // Footer block
    this.doc.setFillColor(...COLOR.card);
    this.doc.rect(0, PAGE_H - 30, PAGE_W, 30, 'F');
    this.doc.setFont('helvetica', 'bold');
    this.doc.setFontSize(9);
    this.doc.setTextColor(...COLOR.amber);
    this.doc.text('Confidential — Strategic Asset', MARGIN, PAGE_H - 18);
    this.doc.setFont('helvetica', 'normal');
    this.doc.setFontSize(8);
    this.doc.setTextColor(...COLOR.muted);
    this.doc.text('Generated by Aetheris AI Studio. Built for execution, not for filing.', MARGIN, PAGE_H - 12);

    this.doc.addPage();
    this.pageNum++;
    this.paintBackground();
    this.drawRunningHeader();
  }

  sectionTitle(label: string, count?: number) {
    this.ensure(18);
    this.y += 4;
    // accent bar
    this.doc.setFillColor(...COLOR.amber);
    this.doc.rect(MARGIN, this.y, 2, 7, 'F');
    this.doc.setFont('helvetica', 'bold');
    this.doc.setFontSize(14);
    this.doc.setTextColor(...COLOR.white);
    this.doc.text(label, MARGIN + 5, this.y + 5.5);
    if (count !== undefined) {
      this.doc.setFont('helvetica', 'normal');
      this.doc.setFontSize(9);
      this.doc.setTextColor(...COLOR.muted);
      const w = this.doc.getTextWidth(label);
      this.doc.text(`(${count})`, MARGIN + 5 + w + 3, this.y + 5.5);
    }
    this.y += 10;
  }

  card(draw: (innerY: number, innerW: number) => number) {
    const startY = this.y;
    const innerX = MARGIN + 4;
    const innerW = CONTENT_W - 8;
    this.y += 4;
    const endY = draw(this.y, innerW);
    this.y = endY + 4;
    const h = this.y - startY;
    if (this.y > PAGE_H - 22) {
    } else {
      this.doc.setDrawColor(...COLOR.border);
      this.doc.setLineWidth(0.2);
      this.doc.setFillColor(...COLOR.card);
      this.doc.roundedRect(MARGIN, startY, CONTENT_W, h, 1.5, 1.5, 'FD');
    }
    this.y += 3;
  }

  paintCard(lines: { text: string; size?: number; bold?: boolean; color?: [number, number, number]; gap?: number }[]) {
    const innerW = CONTENT_W - 8;
    const padTop = 4;
    const padBottom = 5;
    let h = padTop;
    const measured: { wrapped: string[]; size: number; bold: boolean; color: [number, number, number]; gap: number }[] = [];
    for (const ln of lines) {
      const size = ln.size ?? 9.5;
      const bold = ln.bold ?? false;
      const color = ln.color ?? COLOR.text;
      const gap = ln.gap ?? 1.5;
      this.doc.setFont('helvetica', bold ? 'bold' : 'normal');
      this.doc.setFontSize(size);
      const wrapped = this.doc.splitTextToSize(ln.text, innerW);
      measured.push({ wrapped, size, bold, color, gap });
      h += wrapped.length * (size * 0.42) + gap;
    }
    h += padBottom;

    this.ensure(h + 4);
    this.doc.setDrawColor(...COLOR.border);
    this.doc.setLineWidth(0.2);
    this.doc.setFillColor(...COLOR.card);
    this.doc.roundedRect(MARGIN, this.y, CONTENT_W, h, 1.8, 1.8, 'FD');

    let cursor = this.y + padTop;
    for (const m of measured) {
      this.doc.setFont('helvetica', m.bold ? 'bold' : 'normal');
      this.doc.setFontSize(m.size);
      this.doc.setTextColor(...m.color);
      const lh = m.size * 0.42;
      for (const w of m.wrapped) {
        cursor += lh;
        this.doc.text(w, MARGIN + 4, cursor);
      }
      cursor += m.gap;
    }
    this.y += h + 3;
  }

  paragraph(text: string, opts: { size?: number; bold?: boolean; color?: [number, number, number] } = {}) {
    if (!text) return;
    const size = opts.size ?? 10;
    const color = opts.color ?? COLOR.text;
    this.doc.setFont('helvetica', opts.bold ? 'bold' : 'normal');
    this.doc.setFontSize(size);
    this.doc.setTextColor(...color);
    const wrapped = this.doc.splitTextToSize(text, CONTENT_W);
    const lh = size * 0.42;
    for (const line of wrapped) {
      this.ensure(lh + 1);
      this.y += lh;
      this.doc.text(line, MARGIN, this.y);
    }
    this.y += 2;
  }

  finish(filename: string) {
    this.drawFooter();
    this.doc.save(filename);
  }
}

function renderSocialContent(b: PdfBuilder, data: any) {
  if (data.businessName) b.paragraph(`For: ${data.businessName}`, { color: COLOR.muted, size: 9.5 });
  if (data.linkedinPosts?.length) {
    b.sectionTitle('LinkedIn Posts', data.linkedinPosts.length);
    data.linkedinPosts.forEach((p: any, i: number) => {
      b.paintCard([
        { text: `LinkedIn · Post ${i + 1}`, size: 8, bold: true, color: COLOR.blue, gap: 2 },
        ...(p.hook ? [{ text: p.hook, size: 10.5, bold: true, color: COLOR.amber, gap: 2 }] : []),
        ...(p.body ? [{ text: p.body, size: 9.5, color: COLOR.text, gap: 2 }] : []),
        ...(p.cta ? [{ text: `Call to action: ${p.cta}`, size: 9, bold: true, color: COLOR.white }] : []),
      ]);
    });
  }
  if (data.facebookPosts?.length) {
    b.sectionTitle('Facebook Posts', data.facebookPosts.length);
    data.facebookPosts.forEach((p: any, i: number) => {
      b.paintCard([
        { text: `Facebook · Post ${i + 1}`, size: 8, bold: true, color: COLOR.blue, gap: 2 },
        ...(p.hook ? [{ text: p.hook, size: 10.5, bold: true, color: COLOR.amber, gap: 2 }] : []),
        ...(p.body ? [{ text: p.body, size: 9.5, color: COLOR.text, gap: 2 }] : []),
        ...(p.cta ? [{ text: `Call to action: ${p.cta}`, size: 9, bold: true, color: COLOR.white }] : []),
      ]);
    });
  }
  if (data.adHooks?.length) {
    b.sectionTitle('Ad Hooks', data.adHooks.length);
    data.adHooks.forEach((h: any, i: number) => {
      b.paintCard([
        { text: `Ad Hook ${i + 1}`, size: 8, bold: true, color: COLOR.amber, gap: 2 },
        ...(h.headline ? [{ text: h.headline, size: 11, bold: true, color: COLOR.white, gap: 2 }] : []),
        ...(h.subheadline ? [{ text: h.subheadline, size: 9.5, color: COLOR.text, gap: 2 }] : []),
        ...(h.cta ? [{ text: `CTA: ${h.cta}`, size: 9, bold: true, color: COLOR.amber }] : []),
      ]);
    });
  }
}

function renderContentCalendar(b: PdfBuilder, data: any) {
  const days = data.days || [];
  b.sectionTitle('30-Day Content Calendar', days.length);
  days.forEach((d: any) => {
    const meta = [d.platform, d.contentType, d.bestTime].filter(Boolean).join(' · ');
    const tags = (d.hashtags || []).map((h: string) => `#${h.replace('#', '')}`).join(' ');
    b.paintCard([
      { text: `Day ${d.day}${meta ? ' · ' + meta : ''}`, size: 8, bold: true, color: COLOR.amber, gap: 2 },
      ...(d.topic ? [{ text: d.topic, size: 11, bold: true, color: COLOR.white, gap: 2 }] : []),
      ...(d.hook ? [{ text: `"${d.hook}"`, size: 10, bold: true, color: COLOR.amber, gap: 2 }] : []),
      ...(d.caption ? [{ text: d.caption, size: 9.5, color: COLOR.text, gap: 2 }] : []),
      ...(tags ? [{ text: tags, size: 8.5, color: COLOR.blue }] : []),
    ]);
  });
}

function renderSalesScripts(b: PdfBuilder, data: any) {
  const sections: { key: string; label: string }[] = [
    { key: 'coldCalls', label: 'Cold Call Scripts' },
    { key: 'emailScripts', label: 'Email Scripts' },
    { key: 'objectionHandlers', label: 'Objection Handlers' },
    { key: 'closingScripts', label: 'Closing Scripts' },
  ];
  for (const s of sections) {
    const arr = data[s.key];
    if (!arr?.length) continue;
    b.sectionTitle(s.label, arr.length);
    arr.forEach((item: any, i: number) => {
      const text = typeof item === 'string' ? item : (item.script || item.body || '');
      const lines: any[] = [{ text: `${s.label.slice(0, -1)} ${i + 1}`, size: 8, bold: true, color: COLOR.amber, gap: 2 }];
      if (item.title) lines.push({ text: item.title, size: 11, bold: true, color: COLOR.white, gap: 2 });
      if (item.scenario) lines.push({ text: `Scenario: ${item.scenario}`, size: 9, bold: true, color: COLOR.blue, gap: 2 });
      if (item.objection) lines.push({ text: `"${item.objection}"`, size: 10, bold: true, color: COLOR.amber, gap: 2 });
      if (item.subject) lines.push({ text: `Subject: ${item.subject}`, size: 9.5, bold: true, color: COLOR.white, gap: 2 });
      if (text) lines.push({ text, size: 9.5, color: COLOR.text });
      b.paintCard(lines);
    });
  }
}

function renderFollowUp(b: PdfBuilder, data: any) {
  const steps = data.steps || data.touches || data.plan || [];
  b.sectionTitle('Follow-Up Sequence', steps.length);
  steps.forEach((s: any, i: number) => {
    const day = s.day || s.dayNumber || i + 1;
    const meta = [s.channel, s.goal].filter(Boolean).join(' · ');
    const body = s.message || s.body || s.script || '';
    const lines: any[] = [{ text: `Day ${day}${meta ? ' · ' + meta : ''}`, size: 8, bold: true, color: COLOR.amber, gap: 2 }];
    if (s.subject) lines.push({ text: `Subject: ${s.subject}`, size: 10, bold: true, color: COLOR.white, gap: 2 });
    if (body) lines.push({ text: body, size: 9.5, color: COLOR.text });
    b.paintCard(lines);
  });
}

function renderStrategicQuestions(b: PdfBuilder, data: any) {
  const qs = data.questions || data.strategicQuestions || [];
  b.sectionTitle('Strategic Questions', qs.length);
  qs.forEach((q: any, i: number) => {
    const text = typeof q === 'string' ? q : (q.question || q.text || '');
    const lines: any[] = [{ text: `Question ${i + 1}`, size: 8, bold: true, color: COLOR.amber, gap: 2 }];
    if (text) lines.push({ text, size: 10.5, bold: true, color: COLOR.white, gap: 2 });
    if (q.purpose) lines.push({ text: `Why ask it: ${q.purpose}`, size: 9, color: COLOR.text, gap: 2 });
    if (q.followUp) lines.push({ text: `Follow-up: ${q.followUp}`, size: 9, color: COLOR.muted });
    b.paintCard(lines);
  });
}

function renderBrandContradictions(b: PdfBuilder, data: any) {
  const items = data.contradictions || data.findings || [];
  b.sectionTitle('Brand Contradictions', items.length);
  items.forEach((c: any, i: number) => {
    const lines: any[] = [{ text: `Contradiction ${i + 1}`, size: 8, bold: true, color: COLOR.red, gap: 2 }];
    const title = c.title || c.contradiction;
    if (title) lines.push({ text: title, size: 11, bold: true, color: COLOR.white, gap: 2 });
    if (c.claim) lines.push({ text: `Claim: ${c.claim}`, size: 9.5, color: COLOR.text, gap: 2 });
    if (c.reality) lines.push({ text: `Reality: ${c.reality}`, size: 9.5, color: COLOR.text, gap: 2 });
    const fix = c.fix || c.recommendation;
    if (fix) lines.push({ text: `Fix: ${fix}`, size: 9.5, bold: true, color: COLOR.amber });
    b.paintCard(lines);
  });
}

function renderFrictionAudit(b: PdfBuilder, data: any) {
  const items = data.findings || data.frictionPoints || data.audit || [];
  b.sectionTitle('Friction Vocabulary Audit', items.length);
  items.forEach((f: any, i: number) => {
    const phrase = f.phrase || f.term || f.title;
    const problem = f.problem || f.issue;
    const fix = f.suggestion || f.replacement;
    const lines: any[] = [{ text: `Finding ${i + 1}`, size: 8, bold: true, color: COLOR.amber, gap: 2 }];
    if (phrase) lines.push({ text: `"${phrase}"`, size: 11, bold: true, color: COLOR.white, gap: 2 });
    if (problem) lines.push({ text: `Why it hurts: ${problem}`, size: 9.5, color: COLOR.text, gap: 2 });
    if (fix) lines.push({ text: `Replace with: ${fix}`, size: 9.5, bold: true, color: COLOR.amber });
    b.paintCard(lines);
  });
}

function renderGenericJson(b: PdfBuilder, data: any) {
  b.sectionTitle('Output');
  const text = JSON.stringify(data, null, 2);
  b.paragraph(text, { size: 8.5, color: COLOR.muted });
}

export function downloadLibraryItemAsPdf(item: AdminLibraryItem) {
  if (item.tool_type === 'playbook' && item.file_url) {
    window.open(item.file_url, '_blank', 'noopener,noreferrer');
    return;
  }

  const toolLabel = TOOL_LABELS[item.tool_type] || item.tool_type;
  const b = new PdfBuilder(item.title, toolLabel);
  b.drawCover();

  const data = item.output_data as any;
  if (!data || typeof data !== 'object') {
    b.paragraph('No content available.', { color: COLOR.muted });
  } else {
    switch (item.tool_type) {
      case 'social_content': renderSocialContent(b, data); break;
      case 'content_calendar': renderContentCalendar(b, data); break;
      case 'sales_scripts': renderSalesScripts(b, data); break;
      case 'follow_up_plan': renderFollowUp(b, data); break;
      case 'strategic_questions': renderStrategicQuestions(b, data); break;
      case 'brand_contradictions': renderBrandContradictions(b, data); break;
      case 'friction_audit': renderFrictionAudit(b, data); break;
      default: renderGenericJson(b, data);
    }
  }

  const safe = item.title.replace(/[^a-zA-Z0-9-_ ]/g, '').replace(/\s+/g, '_').slice(0, 80) || 'aetheris-library';
  b.finish(`${safe}.pdf`);
}
