import jsPDF from 'jspdf';

/**
 * Aetheris Forensics Playbook PDF.
 * Renders markdown deliverables in the same professional, light-theme style
 * as the rest of the Aetheris Playbooks (white bg, amber accents, helvetica).
 */

const AMBER: [number, number, number] = [217, 167, 71];
const INK: [number, number, number] = [25, 25, 30];
const SUB: [number, number, number] = [110, 110, 120];
const RULE: [number, number, number] = [220, 220, 225];
const SOFT: [number, number, number] = [248, 246, 240];
const CRIMSON: [number, number, number] = [180, 60, 60];

const PAGE_W = 210;
const PAGE_H = 297;
const MARGIN = 18;
const CONTENT_W = PAGE_W - MARGIN * 2;

class W {
  doc: jsPDF;
  y: number;
  pageNum = 1;
  toolLabel: string;
  cardStartY: number | null = null;

  constructor(toolLabel: string) {
    this.doc = new jsPDF({ unit: 'mm', format: 'a4' });
    this.y = MARGIN + 14;
    this.toolLabel = toolLabel;
  }

  drawHeader() {
    this.doc.setFillColor(...AMBER);
    this.doc.rect(0, 0, PAGE_W, 3, 'F');
    this.doc.setFont('helvetica', 'bold');
    this.doc.setFontSize(9);
    this.doc.setTextColor(...INK);
    this.doc.text('AETHERIS', MARGIN, 11);
    this.doc.setFont('helvetica', 'normal');
    this.doc.setFontSize(8);
    this.doc.setTextColor(...SUB);
    this.doc.text(this.toolLabel.toUpperCase(), PAGE_W - MARGIN, 11, { align: 'right' });
    this.doc.setDrawColor(...RULE);
    this.doc.setLineWidth(0.2);
    this.doc.line(MARGIN, 14, PAGE_W - MARGIN, 14);
  }

  drawFooter() {
    const fy = PAGE_H - 12;
    this.doc.setDrawColor(...RULE);
    this.doc.setLineWidth(0.2);
    this.doc.line(MARGIN, fy - 4, PAGE_W - MARGIN, fy - 4);
    this.doc.setFont('helvetica', 'normal');
    this.doc.setFontSize(8);
    this.doc.setTextColor(...SUB);
    this.doc.text('aetheris.technology  ·  Forensic Playbook', MARGIN, fy);
    this.doc.text(`Page ${this.pageNum}`, PAGE_W - MARGIN, fy, { align: 'right' });
  }

  ensure(needed: number) {
    if (this.y + needed > PAGE_H - 22) {
      this.doc.addPage();
      this.pageNum++;
      this.y = MARGIN + 14;
      this.drawHeader();
      this.drawFooter();
    }
  }

  cover(title: string) {
    this.drawHeader();
    this.drawFooter();
    this.doc.setFont('helvetica', 'bold');
    this.doc.setFontSize(11);
    this.doc.setTextColor(...AMBER);
    this.doc.text('AETHERIS  ·  FORENSIC PLAYBOOK', MARGIN, 30);

    this.doc.setFillColor(...AMBER);
    this.doc.rect(MARGIN, 90, 2, 20, 'F');
    this.doc.setFont('helvetica', 'bold');
    this.doc.setFontSize(9);
    this.doc.setTextColor(...AMBER);
    this.doc.text(this.toolLabel.toUpperCase(), MARGIN + 6, 96);

    this.doc.setFont('helvetica', 'bold');
    this.doc.setFontSize(26);
    this.doc.setTextColor(...INK);
    const lines = this.doc.splitTextToSize(title, CONTENT_W);
    let ty = 105;
    for (const line of lines) {
      this.doc.text(line, MARGIN + 6, ty);
      ty += 11;
    }

    this.doc.setFont('helvetica', 'normal');
    this.doc.setFontSize(10);
    this.doc.setTextColor(...SUB);
    this.doc.text(
      `Generated ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`,
      MARGIN + 6,
      ty + 4,
    );

    this.doc.setDrawColor(...AMBER);
    this.doc.setLineWidth(0.6);
    this.doc.line(MARGIN, PAGE_H - 35, MARGIN + 25, PAGE_H - 35);
    this.doc.setFont('helvetica', 'bold');
    this.doc.setFontSize(9);
    this.doc.setTextColor(...INK);
    this.doc.text('Confidential — Forensic Diagnostic', MARGIN, PAGE_H - 28);
    this.doc.setFont('helvetica', 'normal');
    this.doc.setFontSize(8);
    this.doc.setTextColor(...SUB);
    this.doc.text('Generated by Aetheris AI Studio. Built for execution, not for filing.', MARGIN, PAGE_H - 22);

    this.doc.addPage();
    this.pageNum++;
    this.y = MARGIN + 14;
    this.drawHeader();
    this.drawFooter();
  }

  h1(text: string) {
    this.ensure(20);
    this.y += 4;
    this.doc.setFont('helvetica', 'bold');
    this.doc.setFontSize(20);
    this.doc.setTextColor(...INK);
    const lines = this.doc.splitTextToSize(text, CONTENT_W);
    for (const line of lines) {
      this.ensure(10);
      this.y += 9;
      this.doc.text(line, MARGIN, this.y);
    }
    this.doc.setDrawColor(...AMBER);
    this.doc.setLineWidth(0.8);
    this.doc.line(MARGIN, this.y + 2, MARGIN + 28, this.y + 2);
    this.y += 8;
  }

  h2(text: string) {
    this.ensure(16);
    this.y += 6;
    this.doc.setFont('helvetica', 'bold');
    this.doc.setFontSize(13);
    this.doc.setTextColor(...INK);
    this.y += 5;
    this.doc.text(text, MARGIN + 6, this.y);
    this.doc.setFillColor(...AMBER);
    this.doc.rect(MARGIN, this.y - 4, 3, 5, 'F');
    this.y += 3;
  }

  h3(text: string) {
    this.ensure(10);
    this.y += 4;
    this.doc.setFont('helvetica', 'bold');
    this.doc.setFontSize(11);
    this.doc.setTextColor(...AMBER);
    this.y += 5;
    this.doc.text(text, MARGIN, this.y);
    this.y += 1;
  }

  // Renders a paragraph with simple **bold** inline support
  paragraph(text: string, color: [number, number, number] = INK, size = 10) {
    if (!text.trim()) {
      this.y += 2;
      return;
    }
    const lh = size * 0.45;
    this.doc.setFontSize(size);
    this.doc.setTextColor(color[0], color[1], color[2]);

    // tokenize **bold**
    const parts: { text: string; bold: boolean }[] = [];
    const re = /\*\*(.+?)\*\*/g;
    let last = 0;
    let m: RegExpExecArray | null;
    while ((m = re.exec(text)) !== null) {
      if (m.index > last) parts.push({ text: text.slice(last, m.index), bold: false });
      parts.push({ text: m[1], bold: true });
      last = m.index + m[0].length;
    }
    if (last < text.length) parts.push({ text: text.slice(last), bold: false });
    if (parts.length === 0) parts.push({ text, bold: false });

    // word-wrap manually with mixed weights
    let lineParts: { text: string; bold: boolean }[] = [];
    let lineWidth = 0;
    const maxW = CONTENT_W - 4;
    const space = (bold: boolean) => {
      this.doc.setFont('helvetica', bold ? 'bold' : 'normal');
      return this.doc.getTextWidth(' ');
    };
    const flush = () => {
      this.ensure(lh + 1);
      this.y += lh;
      let x = MARGIN + 2;
      for (let i = 0; i < lineParts.length; i++) {
        const p = lineParts[i];
        this.doc.setFont('helvetica', p.bold ? 'bold' : 'normal');
        this.doc.text(p.text, x, this.y);
        x += this.doc.getTextWidth(p.text);
        if (i < lineParts.length - 1) x += space(p.bold);
      }
      lineParts = [];
      lineWidth = 0;
    };
    for (const part of parts) {
      const words = part.text.split(/\s+/).filter(Boolean);
      this.doc.setFont('helvetica', part.bold ? 'bold' : 'normal');
      for (const word of words) {
        const wW = this.doc.getTextWidth(word);
        const sp = lineParts.length ? space(part.bold) : 0;
        if (lineWidth + sp + wW > maxW && lineParts.length) {
          flush();
        }
        lineParts.push({ text: word, bold: part.bold });
        lineWidth += (lineParts.length > 1 ? sp : 0) + wW;
      }
    }
    if (lineParts.length) flush();
    this.y += 1.5;
  }

  bullet(text: string) {
    this.ensure(6);
    const lh = 10 * 0.45;
    this.doc.setFontSize(10);
    this.doc.setTextColor(...AMBER);
    this.doc.setFont('helvetica', 'bold');
    this.y += lh;
    this.doc.text('•', MARGIN + 4, this.y);
    this.y -= lh;
    // shift content right
    const savedY = this.y;
    this._paragraphIndented(text, MARGIN + 9);
    if (this.y < savedY) this.y = savedY;
  }

  _paragraphIndented(text: string, leftX: number) {
    const size = 10;
    const lh = size * 0.45;
    this.doc.setFontSize(size);
    this.doc.setTextColor(...INK);
    const maxW = PAGE_W - MARGIN - leftX;
    // bold support
    const parts: { text: string; bold: boolean }[] = [];
    const re = /\*\*(.+?)\*\*/g;
    let last = 0;
    let m: RegExpExecArray | null;
    while ((m = re.exec(text)) !== null) {
      if (m.index > last) parts.push({ text: text.slice(last, m.index), bold: false });
      parts.push({ text: m[1], bold: true });
      last = m.index + m[0].length;
    }
    if (last < text.length) parts.push({ text: text.slice(last), bold: false });
    if (!parts.length) parts.push({ text, bold: false });

    let lineParts: { text: string; bold: boolean }[] = [];
    let lineWidth = 0;
    const space = (b: boolean) => {
      this.doc.setFont('helvetica', b ? 'bold' : 'normal');
      return this.doc.getTextWidth(' ');
    };
    const flush = () => {
      this.ensure(lh + 1);
      this.y += lh;
      let x = leftX;
      for (let i = 0; i < lineParts.length; i++) {
        const p = lineParts[i];
        this.doc.setFont('helvetica', p.bold ? 'bold' : 'normal');
        this.doc.text(p.text, x, this.y);
        x += this.doc.getTextWidth(p.text);
        if (i < lineParts.length - 1) x += space(p.bold);
      }
      lineParts = [];
      lineWidth = 0;
    };
    for (const part of parts) {
      const words = part.text.split(/\s+/).filter(Boolean);
      this.doc.setFont('helvetica', part.bold ? 'bold' : 'normal');
      for (const word of words) {
        const wW = this.doc.getTextWidth(word);
        const sp = lineParts.length ? space(part.bold) : 0;
        if (lineWidth + sp + wW > maxW && lineParts.length) flush();
        lineParts.push({ text: word, bold: part.bold });
        lineWidth += (lineParts.length > 1 ? sp : 0) + wW;
      }
    }
    if (lineParts.length) flush();
    this.y += 1;
  }

  quote(text: string) {
    this.ensure(10);
    const startY = this.y + 1;
    this._paragraphIndented(text, MARGIN + 8);
    const endY = this.y;
    this.doc.setFillColor(...AMBER);
    this.doc.rect(MARGIN + 2, startY, 1.4, endY - startY, 'F');
    this.y += 1;
  }

  divider() {
    this.ensure(4);
    this.y += 2;
    this.doc.setDrawColor(...RULE);
    this.doc.setLineWidth(0.2);
    this.doc.line(MARGIN, this.y, PAGE_W - MARGIN, this.y);
    this.y += 3;
  }

  table(rows: string[][]) {
    if (!rows.length) return;
    const cols = rows[0].length;
    const colW = (CONTENT_W) / cols;
    const cellPad = 2;
    this.doc.setFontSize(9);
    rows.forEach((row, ri) => {
      // measure
      const lineHeights = row.map(cell => {
        this.doc.setFont('helvetica', ri === 0 ? 'bold' : 'normal');
        const wrapped = this.doc.splitTextToSize(cell, colW - cellPad * 2);
        return wrapped.length;
      });
      const maxLines = Math.max(...lineHeights);
      const rowH = maxLines * 4 + cellPad * 2;
      this.ensure(rowH + 2);
      const y0 = this.y;
      // bg for header
      if (ri === 0) {
        this.doc.setFillColor(...SOFT);
        this.doc.rect(MARGIN, y0, CONTENT_W, rowH, 'F');
      }
      // borders
      this.doc.setDrawColor(...RULE);
      this.doc.setLineWidth(0.15);
      this.doc.rect(MARGIN, y0, CONTENT_W, rowH, 'S');
      // text
      row.forEach((cell, ci) => {
        const x = MARGIN + ci * colW;
        if (ci > 0) this.doc.line(x, y0, x, y0 + rowH);
        this.doc.setFont('helvetica', ri === 0 ? 'bold' : 'normal');
        this.doc.setTextColor(...INK);
        const wrapped = this.doc.splitTextToSize(cell, colW - cellPad * 2);
        wrapped.forEach((line: string, li: number) => {
          this.doc.text(line, x + cellPad, y0 + cellPad + 3 + li * 4);
        });
      });
      this.y = y0 + rowH;
    });
    this.y += 3;
  }

  finish(filename: string) {
    this.doc.save(filename);
  }
}

/** Light markdown → renderer dispatch */
function renderMarkdown(w: W, md: string) {
  const lines = md.replace(/\r\n/g, '\n').split('\n');
  let i = 0;
  while (i < lines.length) {
    const raw = lines[i];
    const line = raw.trimEnd();

    // table block
    if (/^\s*\|/.test(line) && i + 1 < lines.length && /^\s*\|?[\s\-:|]+\|/.test(lines[i + 1])) {
      const tableRows: string[][] = [];
      const parseRow = (l: string) =>
        l.trim().replace(/^\|/, '').replace(/\|$/, '').split('|').map(c => c.trim());
      tableRows.push(parseRow(line));
      i += 2; // skip header + separator
      while (i < lines.length && /^\s*\|/.test(lines[i])) {
        tableRows.push(parseRow(lines[i]));
        i++;
      }
      w.table(tableRows);
      continue;
    }

    if (/^---+$/.test(line)) { w.divider(); i++; continue; }
    if (/^###\s+/.test(line)) { w.h3(line.replace(/^###\s+/, '')); i++; continue; }
    if (/^##\s+/.test(line)) { w.h2(line.replace(/^##\s+/, '')); i++; continue; }
    if (/^#\s+/.test(line)) { w.h1(line.replace(/^#\s+/, '')); i++; continue; }
    if (/^>\s?/.test(line)) {
      // collect contiguous quote lines
      const parts: string[] = [];
      while (i < lines.length && /^>\s?/.test(lines[i])) {
        parts.push(lines[i].replace(/^>\s?/, ''));
        i++;
      }
      w.quote(parts.join(' '));
      continue;
    }
    if (/^\s*[-*]\s+/.test(line)) {
      w.bullet(line.replace(/^\s*[-*]\s+/, ''));
      i++;
      continue;
    }
    if (/^\s*\d+\.\s+/.test(line)) {
      const m = line.match(/^\s*(\d+)\.\s+(.*)$/);
      if (m) {
        w._paragraphIndented(`**${m[1]}.** ${m[2]}`, MARGIN + 4);
        i++;
        continue;
      }
    }
    if (line.trim() === '') {
      w.y += 2;
      i++;
      continue;
    }
    w.paragraph(line);
    i++;
  }
}

export function downloadForensicsPlaybookPdf(opts: {
  title: string;
  toolLabel: string;
  markdown: string;
  filename?: string;
}) {
  const w = new W(opts.toolLabel);
  w.cover(opts.title);
  renderMarkdown(w, opts.markdown);
  const filename =
    opts.filename ||
    `aetheris-${opts.title.replace(/\s+/g, '-').toLowerCase()}.pdf`;
  w.finish(filename);
}
