import React, { useEffect, useMemo, useState } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Loader2, ShieldAlert, ShieldCheck, BookOpen, Copy, Download, Volume2, Square, Trash2 } from 'lucide-react';
import { toast } from '@/hooks/use-toast';
import { supabase } from '@/integrations/supabase/client';
import { saveToolRun } from '@/lib/toolSaveHelper';

type Verdict = 'LEGIT' | 'LIKELY_LEGIT' | 'MIXED' | 'LIKELY_SCAM' | 'SCAM';
type Clue = {
  pattern: string;
  highlight: string;
  fact: string;
  source: string;
  confidence: number;
};
type ScamResult = {
  target: string;
  domain: string;
  score: number;
  verdict: Verdict;
  summary: string;
  bottom_line: string;
  trust_signals: string[];
  red_flags: string[];
  clues: Clue[];
  evidence_excerpt: string;
  raw: { rdap_present: boolean; firecrawl_present: boolean; https_ok: boolean; final_status: number };
};

const verdictColor = (v: Verdict) => {
  switch (v) {
    case 'LEGIT':
    case 'LIKELY_LEGIT':
      return 'text-emerald-400 border-emerald-400/40 bg-emerald-400/10';
    case 'MIXED':
      return 'text-amber border-amber/40 bg-amber/10';
    case 'LIKELY_SCAM':
    case 'SCAM':
      return 'text-crimson border-crimson/40 bg-crimson/10';
  }
};

function renderHighlighted(text: string, clues: Clue[], activeIdx: number | null) {
  if (!text) return null;
  type Span = { start: number; end: number; idx: number };
  const spans: Span[] = [];
  clues.forEach((c, idx) => {
    const needle = (c.highlight || '').trim();
    if (!needle || needle.length < 3) return;
    const lower = text.toLowerCase();
    const i = lower.indexOf(needle.toLowerCase());
    if (i >= 0) spans.push({ start: i, end: i + needle.length, idx });
  });
  spans.sort((a, b) => a.start - b.start);
  const parts: React.ReactNode[] = [];
  let cur = 0;
  spans.forEach((s, k) => {
    if (s.start < cur) return;
    parts.push(<span key={`t-${k}`}>{text.slice(cur, s.start)}</span>);
    const active = activeIdx === s.idx;
    parts.push(
      <mark
        key={`h-${k}`}
        className={`px-1 rounded-sm border-b-2 ${active ? 'bg-crimson/30 border-crimson text-foreground' : 'bg-amber/15 border-amber/60 text-foreground'}`}
      >
        {text.slice(s.start, s.end)}
      </mark>,
    );
    cur = s.end;
  });
  parts.push(<span key="t-end">{text.slice(cur)}</span>);
  return parts;
}

function toEasyRead(r: ScamResult): string {
  const lines: string[] = [];
  lines.push(`AETHERIS — SCAM FORENSICS REPORT`);
  lines.push(`Target: ${r.target}`);
  lines.push(`Domain: ${r.domain}`);
  lines.push(`Date:   ${new Date().toLocaleString()}`);
  lines.push(``);
  lines.push(`VERDICT: ${r.verdict.replace('_', ' ')}  (risk score ${r.score}/100)`);
  lines.push(`${r.summary}`);
  lines.push(``);
  lines.push(`BOTTOM LINE`);
  lines.push(r.bottom_line || '(none)');
  lines.push(``);
  if (r.red_flags?.length) {
    lines.push(`RED FLAGS`);
    r.red_flags.forEach((f, i) => lines.push(`  ${i + 1}. ${f}`));
    lines.push(``);
  }
  if (r.trust_signals?.length) {
    lines.push(`TRUST SIGNALS`);
    r.trust_signals.forEach((f, i) => lines.push(`  ${i + 1}. ${f}`));
    lines.push(``);
  }
  if (r.clues?.length) {
    lines.push(`FORENSIC CLUES`);
    r.clues.forEach((c, i) => {
      lines.push(`  ${String(i + 1).padStart(2, '0')}. ${c.pattern}  [${Math.round((c.confidence || 0) * 100)}% confidence]`);
      if (c.highlight) lines.push(`      Evidence: "${c.highlight}"`);
      if (c.fact) lines.push(`      Why it matters: ${c.fact}`);
      if (c.source) lines.push(`      Source: ${c.source}`);
    });
    lines.push(``);
  }
  lines.push(`TECHNICAL`);
  lines.push(`  HTTPS clean:    ${r.raw.https_ok ? 'yes' : 'NO'}`);
  lines.push(`  Final status:   ${r.raw.final_status}`);
  lines.push(`  WHOIS pulled:   ${r.raw.rdap_present ? 'yes' : 'no'}`);
  lines.push(`  Page scraped:   ${r.raw.firecrawl_present ? 'yes' : 'no'}`);
  lines.push(``);
  lines.push(`— Generated by Aetheris Scam Forensics`);
  return lines.join('\n');
}

const EasyReadPanel: React.FC<{ text: string; subject: string }> = ({ text, subject }) => {
  const [speaking, setSpeaking] = useState(false);
  const copy = async () => {
    await navigator.clipboard.writeText(text);
    toast({ title: 'Copied to clipboard' });
  };
  const download = () => {
    const blob = new Blob(['\uFEFF', text], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    const safe = (subject || 'scam-report').replace(/[^a-z0-9-_]+/gi, '-').toLowerCase();
    a.download = `${safe}-scam-forensics-${new Date().toISOString().slice(0, 10)}.txt`;
    document.body.appendChild(a);
    a.click();
    a.remove();
    URL.revokeObjectURL(url);
  };
  const speak = () => {
    if (typeof window === 'undefined' || !('speechSynthesis' in window)) {
      toast({ title: 'Read-aloud not supported', variant: 'destructive' });
      return;
    }
    if (speaking) { window.speechSynthesis.cancel(); setSpeaking(false); return; }
    const u = new SpeechSynthesisUtterance(text);
    u.onend = () => setSpeaking(false);
    u.onerror = () => setSpeaking(false);
    window.speechSynthesis.cancel();
    window.speechSynthesis.speak(u);
    setSpeaking(true);
  };
  useEffect(() => () => { if (typeof window !== 'undefined' && 'speechSynthesis' in window) window.speechSynthesis.cancel(); }, []);

  return (
    <div className="rounded-sm border border-emerald-400/30 bg-emerald-400/5 p-4 space-y-3">
      <div className="flex items-center gap-2 flex-wrap">
        <BookOpen className="w-4 h-4 text-emerald-400" />
        <div className="text-[10px] uppercase tracking-widest font-bold text-emerald-400">Easy Read Mode</div>
        <div className="text-[10px] text-muted-foreground">Plain English — copy, download, or read aloud.</div>
        <div className="ml-auto flex items-center gap-1.5">
          <Button variant="outline" size="sm" onClick={copy} className="h-7 text-[11px]"><Copy className="w-3 h-3 mr-1" /> Copy</Button>
          <Button variant="outline" size="sm" onClick={download} className="h-7 text-[11px]"><Download className="w-3 h-3 mr-1" /> Download</Button>
          <Button variant="outline" size="sm" onClick={speak} className="h-7 text-[11px]">
            {speaking ? <Square className="w-3 h-3 mr-1" /> : <Volume2 className="w-3 h-3 mr-1" />}
            {speaking ? 'Stop' : 'Read aloud'}
          </Button>
        </div>
      </div>
      <pre className="text-xs leading-relaxed whitespace-pre-wrap font-sans text-foreground/90 max-h-[360px] overflow-y-auto">{text}</pre>
    </div>
  );
};

export const ScamCheckCard: React.FC = () => {
  const [url, setUrl] = useState('');
  const [busy, setBusy] = useState(false);
  const [result, setResult] = useState<ScamResult | null>(null);
  const [activeIdx, setActiveIdx] = useState<number | null>(null);

  const run = async () => {
    if (!url.trim()) { toast({ title: 'Enter a URL', variant: 'destructive' }); return; }
    setBusy(true); setResult(null); setActiveIdx(null);
    try {
      const { data, error } = await supabase.functions.invoke('scam-check', { body: { url: url.trim() } });
      if (error) throw error;
      if (!data?.ok) throw new Error(data?.error || 'Scan failed');
      const r: ScamResult = data.result;
      setResult(r);
      saveToolRun({
        tool_type: 'scam_check',
        title: `Scam Forensics — ${r.domain}`,
        input_data: { url: r.target },
        output_data: r as unknown as Record<string, unknown>,
      });
    } catch (e: any) {
      toast({ title: 'Scan failed', description: e?.message || 'Try again', variant: 'destructive' });
    } finally {
      setBusy(false);
    }
  };

  const easy = useMemo(() => result ? toEasyRead(result) : '', [result]);
  const highlighted = useMemo(() => result ? renderHighlighted(result.evidence_excerpt || '', result.clues || [], activeIdx) : null, [result, activeIdx]);

  return (
    <div className="space-y-4">
      <div className="rounded-sm border border-crimson/30 bg-crimson/5 p-4 space-y-3">
        <div className="flex items-center gap-2">
          <ShieldAlert className="w-5 h-5 text-crimson" />
          <h3 className="font-display text-lg font-bold tracking-wide">Scam / Legitimacy Forensics</h3>
        </div>
        <p className="text-xs text-muted-foreground">
          Pulls live data — domain registration (RDAP), redirect chain, SSL, page content — and produces a forensic verdict with cited clues. Same engine pattern as the AI Writing Detector.
        </p>
        <div className="flex gap-2">
          <Input
            placeholder="https://suspicious-site.com"
            value={url}
            onChange={(e) => setUrl(e.target.value)}
            onKeyDown={(e) => { if (e.key === 'Enter') run(); }}
            disabled={busy}
          />
          <Button onClick={run} disabled={busy} className="bg-crimson hover:bg-crimson/90 text-white font-bold">
            {busy ? <Loader2 className="w-4 h-4 animate-spin mr-1" /> : <ShieldAlert className="w-4 h-4 mr-1" />}
            {busy ? 'Investigating…' : 'Run Forensics'}
          </Button>
          {result && (
            <Button variant="outline" onClick={() => { setResult(null); setUrl(''); }}>
              <Trash2 className="w-4 h-4" />
            </Button>
          )}
        </div>
      </div>

      {result && (
        <div className="space-y-4">
          <div className="rounded-sm border border-border bg-background/30 p-4 space-y-3">
            <div className="flex items-center gap-3 flex-wrap">
              <div className="text-[10px] font-mono uppercase tracking-widest text-amber font-bold">
                {result.domain}
              </div>
              <div className={`px-2 py-1 rounded-sm border text-[10px] font-bold uppercase tracking-widest ${verdictColor(result.verdict)}`}>
                {result.verdict.replace('_', ' ')}
              </div>
              <div className="font-display text-2xl font-bold text-foreground">
                {result.score}<span className="text-muted-foreground text-xs font-normal">/100 risk</span>
              </div>
              {result.verdict === 'LEGIT' || result.verdict === 'LIKELY_LEGIT' ? (
                <ShieldCheck className="w-5 h-5 text-emerald-400" />
              ) : (
                <ShieldAlert className="w-5 h-5 text-crimson" />
              )}
            </div>

            <div className="h-1.5 w-full bg-background/40 border border-border rounded-sm overflow-hidden">
              <div className="h-full bg-gradient-to-r from-emerald-400 via-amber to-crimson transition-all" style={{ width: `${result.score}%` }} />
            </div>

            <p className="text-sm text-foreground/90 italic">{result.summary}</p>
            {result.bottom_line && (
              <div className="rounded-sm border border-amber/30 bg-amber/5 p-3">
                <div className="text-[10px] uppercase tracking-widest font-bold text-amber mb-1">Bottom Line</div>
                <p className="text-xs text-foreground/90">{result.bottom_line}</p>
              </div>
            )}

            <div className="grid md:grid-cols-2 gap-3">
              {result.red_flags?.length > 0 && (
                <div className="rounded-sm border border-crimson/30 bg-crimson/5 p-3">
                  <div className="text-[10px] uppercase tracking-widest font-bold text-crimson mb-2">Red Flags</div>
                  <ul className="text-xs space-y-1 text-foreground/90 list-disc pl-4">
                    {result.red_flags.map((f, i) => <li key={i}>{f}</li>)}
                  </ul>
                </div>
              )}
              {result.trust_signals?.length > 0 && (
                <div className="rounded-sm border border-emerald-400/30 bg-emerald-400/5 p-3">
                  <div className="text-[10px] uppercase tracking-widest font-bold text-emerald-400 mb-2">Trust Signals</div>
                  <ul className="text-xs space-y-1 text-foreground/90 list-disc pl-4">
                    {result.trust_signals.map((f, i) => <li key={i}>{f}</li>)}
                  </ul>
                </div>
              )}
            </div>

            {result.evidence_excerpt && (
              <div>
                <div className="text-[10px] uppercase tracking-widest font-bold text-amber mb-1">Live Evidence (highlighted)</div>
                <div className="rounded-sm border border-amber/20 bg-background/40 p-3 text-xs leading-relaxed whitespace-pre-wrap font-mono max-h-[280px] overflow-y-auto">
                  {highlighted}
                </div>
              </div>
            )}

            <div>
              <div className="text-[10px] uppercase tracking-widest font-bold text-amber mb-2">Forensic Clues</div>
              <ol className="space-y-2">
                {(result.clues || []).map((c, i) => (
                  <li
                    key={i}
                    onMouseEnter={() => setActiveIdx(i)}
                    onMouseLeave={() => setActiveIdx(null)}
                    className={`rounded-sm border p-2.5 transition-colors cursor-default ${activeIdx === i ? 'border-crimson bg-crimson/5' : 'border-border bg-background/30 hover:border-amber/50'}`}
                  >
                    <div className="flex items-start gap-2.5">
                      <span className="font-mono text-amber font-bold shrink-0 text-xs">{String(i + 1).padStart(2, '0')}.</span>
                      <div className="flex-1 space-y-1.5 min-w-0">
                        <div className="flex items-center justify-between gap-2 flex-wrap">
                          <div className="font-semibold text-foreground text-xs">{c.pattern}</div>
                          <div className="text-[9px] font-mono uppercase tracking-widest text-muted-foreground">
                            {Math.round((c.confidence || 0) * 100)}%
                          </div>
                        </div>
                        {c.highlight && (
                          <div className="text-[11px]">
                            <span className="bg-amber/15 border-b-2 border-amber/60 px-1 rounded-sm font-serif italic text-foreground">"{c.highlight}"</span>
                          </div>
                        )}
                        {c.fact && <div className="text-[11px] text-foreground/80">{c.fact}</div>}
                        {c.source && (
                          <div className="text-[10px] text-muted-foreground flex items-start gap-1.5">
                            <BookOpen className="w-3 h-3 mt-0.5 text-amber shrink-0" />
                            <span>{c.source}</span>
                          </div>
                        )}
                      </div>
                    </div>
                  </li>
                ))}
              </ol>
            </div>
          </div>

          <EasyReadPanel text={easy} subject={result.domain} />
        </div>
      )}
    </div>
  );
};

export default ScamCheckCard;
