UPDATE public.careers_questions SET is_active = false WHERE id IN (
  '78a327c6-f499-445f-8ae0-a9a05ff804ab',
  '9910574f-f841-42e2-9cde-fecae319c38c',
  '920b7d6e-0e2a-4497-affc-ed1ca0746554',
  'e209a56a-7c22-46c8-b921-732945e2b0b9',
  'b74d4554-9d9c-446b-9d04-90f3d5cf925d',
  '93375ec1-05b1-42be-ad33-21b0a2e65745',
  '47b6f707-fcb8-4d29-aca9-75f7cc2ddd7d',
  'c4bb9854-805e-4773-b15e-ac501a8bbd05',
  'e0910c45-4bd3-4e08-be13-c308165972e0'
);

INSERT INTO public.careers_questions (question, choices, correct_choice_id, category, difficulty, is_active) VALUES
('What is Aetheris actually selling to clients?',
 '[{"id":"a","text":"A suite of tools"},{"id":"b","text":"An operator who wields the tools for them"},{"id":"c","text":"A SaaS subscription"},{"id":"d","text":"A marketing retainer"}]'::jsonb,
 'b', 'positioning', 1, true),
('How many public offers are in the lineup?',
 '[{"id":"a","text":"3 bundles only"},{"id":"b","text":"2 flagships only"},{"id":"c","text":"5 — three bundles plus two flagships"},{"id":"d","text":"12 individual tools"}]'::jsonb,
 'c', 'pricing', 1, true),
('What is the Signal Pack price?',
 '[{"id":"a","text":"$1,500"},{"id":"b","text":"$2,500"},{"id":"c","text":"$5,000"},{"id":"d","text":"$10,000"}]'::jsonb,
 'b', 'pricing', 1, true),
('What is the Revenue Pack price?',
 '[{"id":"a","text":"$2,500"},{"id":"b","text":"$3,500"},{"id":"c","text":"$5,000"},{"id":"d","text":"$7,500"}]'::jsonb,
 'c', 'pricing', 1, true),
('What is the Operator Suite price?',
 '[{"id":"a","text":"$5,000"},{"id":"b","text":"$7,500"},{"id":"c","text":"$10,000"},{"id":"d","text":"$15,000"}]'::jsonb,
 'c', 'pricing', 1, true),
('What is the flagship 21-Day Revenue Diagnostic price?',
 '[{"id":"a","text":"$10,000"},{"id":"b","text":"$15,000"},{"id":"c","text":"$18,500"},{"id":"d","text":"$25,000"}]'::jsonb,
 'c', 'pricing', 1, true),
('What is the Implementation Retainer price and minimum?',
 '[{"id":"a","text":"$10,000/mo · 1-month minimum"},{"id":"b","text":"$15,000/mo · 3-month minimum"},{"id":"c","text":"$15,000 one-time"},{"id":"d","text":"$25,000/mo · 6-month minimum"}]'::jsonb,
 'b', 'pricing', 1, true),
('Who can purchase the Implementation Retainer?',
 '[{"id":"a","text":"Anyone off the website"},{"id":"b","text":"Only clients who completed the 21-Day Revenue Diagnostic"},{"id":"c","text":"Only existing Operator Suite buyers"},{"id":"d","text":"Only enterprise leads"}]'::jsonb,
 'b', 'pricing', 2, true),
('What does the Operator Suite credit toward?',
 '[{"id":"a","text":"Nothing — standalone"},{"id":"b","text":"The Signal Pack"},{"id":"c","text":"1:1 toward the Implementation Retainer"},{"id":"d","text":"A discount on the Diagnostic"}]'::jsonb,
 'c', 'pricing', 2, true),
('What is the rep commission on every operator-led bundle?',
 '[{"id":"a","text":"Flat 15% of the sale"},{"id":"b","text":"Flat 20% of the sale"},{"id":"c","text":"Tiered 30/25/20 by price"},{"id":"d","text":"$1,000 fixed"}]'::jsonb,
 'b', 'commission', 1, true),
('What does the rep earn for each 21-Day Revenue Diagnostic close?',
 '[{"id":"a","text":"15% = $2,775"},{"id":"b","text":"20% = $3,700"},{"id":"c","text":"$5,000 fixed"},{"id":"d","text":"$7,500 fixed"}]'::jsonb,
 'c', 'commission', 1, true),
('What does the rep earn EVERY MONTH the Implementation Retainer client stays subscribed?',
 '[{"id":"a","text":"$1,500/mo"},{"id":"b","text":"$2,500/mo"},{"id":"c","text":"$4,000/mo"},{"id":"d","text":"One-time $5,000 then nothing"}]'::jsonb,
 'c', 'commission', 1, true),
('A client signs the 21-Day Diagnostic, then a 6-month Retainer. How much does the closing rep make total?',
 '[{"id":"a","text":"$5,000"},{"id":"b","text":"$9,000"},{"id":"c","text":"$24,000"},{"id":"d","text":"$29,000 ($5K + 6 × $4K)"}]'::jsonb,
 'd', 'commission', 2, true),
('Are single tools sold to the public anymore?',
 '[{"id":"a","text":"Yes — full a la carte catalog"},{"id":"b","text":"No — public lineup is bundles + flagships only"},{"id":"c","text":"Only on Black Friday"},{"id":"d","text":"Only to enterprise"}]'::jsonb,
 'b', 'positioning', 2, true),
('When a prospect ghosts after the Signal Pack, you?',
 '[{"id":"a","text":"Mark dead"},{"id":"b","text":"Send a value follow-up referencing one specific leak the operator surfaced"},{"id":"c","text":"Email daily"},{"id":"d","text":"Discount the Revenue Pack"}]'::jsonb,
 'b', 'sales', 1, true),
('Which bundle is the entry point — the operator memo that names the dollar bleed?',
 '[{"id":"a","text":"Signal Pack"},{"id":"b","text":"Revenue Pack"},{"id":"c","text":"Operator Suite"},{"id":"d","text":"21-Day Diagnostic"}]'::jsonb,
 'a', 'sales', 1, true),
('Which bundle rebuilds the sales engine — scripts, follow-up, questions, calendar as one engine?',
 '[{"id":"a","text":"Signal Pack"},{"id":"b","text":"Revenue Pack"},{"id":"c","text":"Operator Suite"},{"id":"d","text":"Implementation Retainer"}]'::jsonb,
 'b', 'sales', 1, true),
('Which offer puts an embedded operator running the full stack for 3 weeks?',
 '[{"id":"a","text":"Signal Pack"},{"id":"b","text":"Revenue Pack"},{"id":"c","text":"Operator Suite"},{"id":"d","text":"21-Day Diagnostic"}]'::jsonb,
 'c', 'sales', 1, true),
('The flagship Diagnostic and Retainer require what before the sale?',
 '[{"id":"a","text":"A signed NDA"},{"id":"b","text":"A 15-minute fit call"},{"id":"c","text":"A wire transfer"},{"id":"d","text":"Nothing — instant checkout"}]'::jsonb,
 'b', 'sales', 2, true),
('The partner (Braden) earns what on a Diagnostic close and on every Retainer month?',
 '[{"id":"a","text":"$1,000 / $1,000/mo"},{"id":"b","text":"$2,000 / $2,000/mo"},{"id":"c","text":"$3,000 / $3,000/mo"},{"id":"d","text":"$5,000 / $5,000/mo"}]'::jsonb,
 'c', 'commission', 2, true);